config/routes.rb
Auth::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  match "/auth/:provider/callback", to: "sessions#create"
  match "/authenticate", to: "authenticate#index"
  match "ditt-tips-develop.dev", to: "home#index"
  match "/auth/failure", to: "sessions#failure"
  match "/tips/nytt",    to: "tips#new", as: "new_tips"
  match "/profil",    to: "profile#index", as: "profile"
  match "/visar-alla-tips/:id",    to: "browse#index", as: "browse"
  match "/bli-medlem", to: "identities#new", as: "register"
  match "/visa-tips/:id", to: "showtip#index", as: "show_tip"
  match "/logout", to: "sessions#destroy", :as => "logout"
  match "/profile", to: "profile#index", :as => "user_profile"
  match "/kategorier", to: "categories#index", :as => "cats"

  resources :categories
  resources :identities
  resources :tips
  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/browse.rb
class Browse < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	 has_many :tips
end

app/models/home.rb
class Home < ActiveRecord::Base
  @latestfive = Tip.scoped(:limit => 5)
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/tip.rb
class Tip < ActiveRecord::Base
	attr_accessible :user_id, :title, :text, :image, :categorie_id
	mount_uploader :image, AvatarUploader
	belongs_to :user
	belongs_to :category
	validates_presence_of   :title
    validates_uniqueness_of :title
    validates_presence_of   :text
    scope :latest_five, where("id > 0")
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
  has_many :tips
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
	def index
    	@tip_by_cat = Tip.where("categorie_id = ?", params[:id]).paginate(:page => params[:page], :per_page => 10)
    	@cat_id = params[:id]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_filter :require_login
	def index
	end
end

app/controllers/showtip_controller.rb
class ShowtipController < ApplicationController
	def index
	    @tip  = Tip.find(params[:id])
	    #Tip.update_all("popularity = 1") #OBS: make this one if nil error occur
	    @update_value = @tip.popularity + 1
	    a = Tip.find_by_id(params[:id])
		a.popularity = @update_value
		a.save
	    @user = User.find(@tip.user_id)
	    respond_to do |format|
	    format.html # show.html.erb
	    format.json { render json: @tip }
    end
  end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_filter :require_login 
  respond_to :html, :json
  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.where(:user_id => session[:user_id]).paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tips }
    end
  end
  
  # GET /tips/1
  # GET /tips/1.json
  def show
    @tip  = Tip.find(params[:id])
    @user = User.find(@tip.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/new
  # GET /tips/new.json
  def new
    @tip = Tip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/1/edit
  def edit
    @tip = Tip.find(params[:id])
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(params[:tip])
  
    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Ditt tips skapades utan problem.' }
        format.json { render json: @tip, status: :created, location: @tip }
      else
        format.html { render action: "new" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tips/1
  # PUT /tips/1.json
  def update
    @tip = Tip.find(params[:id])

    respond_to do |format|
      if @tip.update_attributes(params[:tip])
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy

    respond_to do |format|
      format.html { redirect_to tips_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_email_by_id(id=nil)
		@user = Identity.find(id)
		if @user
			user.email

    end
  end
  def latest_five
    @latest_five = Tip.latest_five 
  end
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/browse_helper.rb
module BrowseHelper
	def fetch_statistics_ui_gui(catid)
		@category = Category.where("id = ?", catid)
		@count = 0
		@category.each do |category|
			@name  = category.categoryname
		end
		@tip = Tip.where("categorie_id = ?", catid)
		@tip.each_with_index do |tip, i|
			@hmany = i + 1
		end
		content_tag(:h1, @hmany.to_s + " traffar i kategorin " + @name)	
		#content_tag(:h1, pluralize(@hmany, 'traff') + " i kategorin #{@name}")
	end		
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/showtip_helper.rb
module ShowtipHelper
	def rating_gui(intCount) # Ugly solution for dipslay rating hearts
		if intCount <= 50
			image_tag "/assets/popularity/hearts_first.png"
		else if intCount >= 51 and intCount < 101
			image_tag "/assets/popularity/hearts_second.png"
		else if intCount >= 101 and intCount < 201
			image_tag "/assets/popularity/hearts_third.png"
		else if intCount >= 201 and intCount < 301
			image_tag "/assets/popularity/hearts_tfour.png"
		else if intCount >= 301
			image_tag "/assets/popularity/hearts_five.png"
		end
		end
		end
		end
		end
	end
end

app/helpers/tips_helper.rb
module TipsHelper
	def facebook_like
    	content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=true&width=450&action=like&font=arial&colorscheme=light&height=80", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
    end
    def fetchCname(id)
    	findc = Category.find(id)
    	findc.categoryname
    end
end

app/views/browse/index.html.erb
<%= fetch_statistics_ui_gui(@cat_id) %>

<%= link_to "Nytt tips i denna kategorin", new_tips_path %>
<p id="notice"><%= notice %></p>
<% #cycle("even", "odd") %>

<% @tip_by_cat.each do |tip| %>
    <div id="tipholder" class="container_12">
      <div id="boxbody" class="container_12">
        <div class="grid_7">
          <div class="imageHolder">
            <%= link_to (image_tag tip.image_url(:thumb)), show_tip_url(tip.id) if tip.image? %> 
          </div>
          <div class="infoHolder">
            <%= link_to tip.title, show_tip_url(tip.id) %>
            <p><%= tip.text %></p>
          </div>
        </div>
        <div class="userHolder">
          <div class="grid_3">Användare</div>
        </div>
      </div>
    </div>

<% end %>
</table>
<div class="apple_pagination">
    <div clas="page_info">
   
    </div>
  </div>

app/views/tips/_form.html.erb
<%= form_for @tip, :html => {:multipart => true} do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

      <ul>
      <% @tip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
   <%= f.label "Kategori" %><br />
 <%= f.select :categorie_id, Category.all.collect {|category| [category.categoryname, category.id]}  %>
  </div>
  <div class="field">
    <%= f.label "Bild" %><br />
    <%= f.file_field :image %>
  </div>
   <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
  </div>
  <div class="actions">
    <%= f.submit :value => "Lägg till tips" %>
  </div>
<% end %>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

<%= link_to 'Show', @tip %> |
<%= link_to 'Back', tips_path %>

app/views/tips/index.html.erb
<h1>Dina tips du har gjort</h1>
<% if @tips.empty? %>
  <p>Du har för tillfället inga tips, lägg till ett nedan.</p>
<% else %>

<% @tips.each do |tip| %>
<div id="tipholder" class="container_12">
      <div id="boxbody" class="container_12">
        <div class="grid_7">
          <div class="imageHolder">
            <%= link_to (image_tag tip.image_url(:thumb)), show_tip_url(tip.id) if tip.image? %> 
          </div>
          <div class="infoHolder">
           <h3><%= best_in_place tip, :title %> <%= image_tag "/assets/icons/page_white_edit.png" %></h3> 
          <p><%= best_in_place tip, :text, :type => :textarea %> 
          <%= image_tag "/assets/icons/page_white_edit.png" %></p>
          Tillhör följande kategori:  <%= fetchCname(tip.categorie_id) %>
          </div>
        </div>
        <div class="userHolder">
          <div style="margin-top: 50px;" class="grid_2"><%= link_to (image_tag "/assets/icons/eye.png"), tip %>
          <%= link_to (image_tag "/assets/icons/page_edit.png"), edit_tip_path(tip) %>
         <%= link_to (image_tag "/assets/icons/exclamation.png"), tip, confirm: 'Are you sure?', method: :delete %></div>
        </div>
      </div>
    </div>
<% end %>
<% end %>
<div class="apple_pagination">
    <div clas="page_info">
     <%= will_paginate @tips %>
    </div>
  </div>
<%= link_to "Skapa ett nytt tips", new_tips_path %>

app/views/tips/new.html.erb
<h1>Lägg till nytt tips</h1>
<%= render 'form' %>

<%= link_to 'Back', tips_path %>

app/views/tips/show.html.erb
<p>
  <b>Title:</b>
  <%= best_in_place @tip, :title %>
</p>

<p>
  <b>Text:</b>
  <%= best_in_place @tip, :text, :type => :textarea %>
</p>

<p>
  <b>Image:</b>
  <%= image_tag @tip.image_url, :width => '150x150' if @tip.image? %>


</p>

<p>
  <b>User:</b>
  <%= @user.name %>
</p>
<p style="">
<%= facebook_like %>
</p>


<%= link_to 'Edit', edit_tip_path(@tip) %> |
<%= link_to 'Back', tips_path %>