config/routes.rb
Auth::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  match "/auth/:provider/callback", to: "sessions#create"
  match "/authenticate", to: "authenticate#index"
  match "ditt-tips-develop.dev", to: "home#index"
  match "/auth/failure", to: "sessions#failure"
  match "/tips/nytt",    to: "tips#new", as: "new_tips"
  match "/profil",    to: "profile#index", as: "profile"
  match "/visar-alla-tips/:id",    to: "browse#index", as: "browse"
  match "/bli-medlem", to: "identities#new", as: "register"
  match "/visa-tips/:id", to: "showtip#index", as: "show_tip"
  match "/logout", to: "sessions#destroy", :as => "logout"
  match "/profile", to: "profile#index", :as => "user_profile"
  match "/kategorier", to: "categories#index", :as => "cats"

  resources :categories
  resources :identities
  resources :tips
  root to: "home#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/browse.rb
class Browse < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	 has_many :tips
end

app/models/home.rb
class Home < ActiveRecord::Base
  @latestfive = Tip.scoped(:limit => 5)
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/tip.rb
class Tip < ActiveRecord::Base
	attr_accessible :user_id, :title, :text, :image, :categorie_id
	mount_uploader :image, AvatarUploader
	belongs_to :user
	belongs_to :category
	validates_presence_of   :title
    validates_uniqueness_of :title
    validates_presence_of   :text
    scope :latest_five, where("id > 0")
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
  has_many :tips
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  scope :for_voter, lambda { |*args| where(["voter_id = ? AND voter_type = ?", args.first.id, args.first.class.name]) }
  scope :for_voteable, lambda { |*args| where(["voteable_id = ? AND voteable_type = ?", args.first.id, args.first.class.name]) }
  scope :recent, lambda { |*args| where(["created_at > ?", (args.first || 2.weeks.ago)]) }
  scope :descending, order("created_at DESC")

  belongs_to :voteable, :polymorphic => true
  belongs_to :voter, :polymorphic => true

  attr_accessible :vote, :voter, :voteable


  # Comment out the line below to allow multiple votes per user.
  validates_uniqueness_of :voteable_id, :scope => [:voteable_type, :voter_type, :voter_id]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_filter :require_login 
  respond_to :html, :json
  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.where(:user_id => session[:user_id]).paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tips }
    end
  end
  
  # GET /tips/1
  # GET /tips/1.json
  def show
    @tip  = Tip.find(params[:id])
    @user = User.find(@tip.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/new
  # GET /tips/new.json
  def new
    @tip = Tip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tip }
    end
  end

  # GET /tips/1/edit
  def edit
    @tip = Tip.find(params[:id])
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(params[:tip])
  
    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Ditt tips skapades utan problem.' }
        format.json { render json: @tip, status: :created, location: @tip }
      else
        format.html { render action: "new" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tips/1
  # PUT /tips/1.json
  def update
    @tip = Tip.find(params[:id])

    respond_to do |format|
      if @tip.update_attributes(params[:tip])
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip = Tip.find(params[:id])
    @tip.destroy

    respond_to do |format|
      format.html { redirect_to tips_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_email_by_id(id=nil)
		@user = Identity.find(id)
		if @user
			user.email

    end
  end
  def latest_five
    @latest_five = Tip.latest_five 
  end
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/browse_helper.rb
module BrowseHelper
	def fetch_statistics_ui_gui(catid)
		@category = Category.where("id = ?", catid)
		@count = 0
		@category.each do |category|
			@name  = category.categoryname
		end
		@tip = Tip.where("categorie_id = ?", catid)
		@tip.each_with_index do |tip, i|
			@hmany = i + 1
		end
		content_tag(:h1, @hmany.to_s + " traffar i kategorin " + @name)	
		#content_tag(:h1, pluralize(@hmany, 'traff') + " i kategorin #{@name}")
	end		
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/showtip_helper.rb
module ShowtipHelper
	def rating_gui(intCount) # Ugly solution for dipslay rating hearts
		if intCount <= 50
			image_tag "/assets/popularity/hearts_first.png"
		else if intCount >= 51 and intCount < 101
			image_tag "/assets/popularity/hearts_second.png"
		else if intCount >= 101 and intCount < 201
			image_tag "/assets/popularity/hearts_third.png"
		else if intCount >= 201 and intCount < 301
			image_tag "/assets/popularity/hearts_tfour.png"
		else if intCount >= 301
			image_tag "/assets/popularity/hearts_five.png"
		end
		end
		end
		end
		end
	end
end

app/helpers/tips_helper.rb
module TipsHelper
	def facebook_like
    	content_tag :iframe, nil, :src => "http://www.facebook.com/plugins/like.php?href=#{CGI::escape(request.url)}&layout=standard&show_faces=true&width=450&action=like&font=arial&colorscheme=light&height=80", :scrolling => 'no', :frameborder => '0', :allowtransparency => true, :id => :facebook_like
    end
    def fetchCname(id)
    	findc = Category.find(id)
    	findc.categoryname
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<link  href="http://fonts.googleapis.com/css?family=Quattrocento+Sans:regular" rel="stylesheet" type="text/css" >    <title>www.ditt-tips.se, tipsa om vad du vill när du vill!</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
<body>

<div class="container_12 clear-block">
 <div style="display: none;" id="login_form">
        <%= form_tag "/auth/identity/callback", :class => "login" do %>
        <div class="field">
          <%= label_tag :auth_key, "Email" %><br>
          <%= text_field_tag :auth_key %>
        </div>
        <div class="field">
          <%= label_tag :password %><br>
          <%= password_field_tag :password %>
        </div>
        <div class="actions"><%= submit_tag "Login" %></div>
        <% end %>
    </div>
     <div style="display: none;" id="overlay">
     </div>
	<div class="conatiner_12" id="header">
		<div class="grid_5" id="logos">
			<a href="">
  				<%= link_to image_tag("logo.png", :alt => "Hemsida"), root_url %>
			</a>
		</div>
		<div class="grid_4" id="nav">
			<ul>
			    <li>
			      <%= link_to image_tag("menu_home.png", :mouseover => "menu_home_hover.png", :alt => "Hemsida"), root_url %>
			      
			    </li>
			     <li>
			       <%= link_to image_tag("menu_member.png", :mouseover => "menu_member_hover.png", :alt => "Medlem"), register_url %>
			    </li>
			     <li>
			      
			        <%= link_to image_tag("menu_browse.png", :mouseover => "menu_browse_hover.png", :alt => "Sök"), cats_url %>
			      
			    </li>
			      <li>
			        <%= link_to image_tag("menu_contact.png", :mouseover => "menu_contact_hover.png", :alt => "Kontakt"), "/kontakt" %>
			      </a>
			    </li>
	  		</ul>
		</div>
		<div class="grid_3" id="login">
		<% if  !current_user %>
			<%= link_to image_tag("sign_in_btn.png", :onclick => "return false", 
	                             :mouseover => "sign_in_btn_hover.png",  
	                             :id => "login_btn"), "#" %>
           	<% else %>
           	<div id="logout_btn" class="grid_2">
           	<%= link_to image_tag("/assets/log_out_btn.png"), logout_path %> 
           	</div>       
        <% end %>
		</div>
	</div>

	<div class="container_12" id="header-inner">
	<div id="admin_menu">
		<% if  current_user %>
			<%= link_to "Mina tips", "/tips" %> 
			<%= link_to "Min profil", user_profile_path %>
		<% end %>
		</div>
	</div>
	<div class="container_12">
	<div id="main">
		
		<div class="grid_9" id="content">
			<% flash.each do |name, msg| %>
	          <%= content_tag :div, msg, :id => "flash_#{name}" %>
	        <% end %>
			<%= yield %>
		</div>
	</div>
	</div>
	<div id="footer">
		<p>www.ditt-tips.se</p>
	</div>

</div>
</body>
</html>